import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedLOCATIONWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedSearchingWidget2.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedGroup78Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedRectangle2597Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedArrow_backWidget4.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedNewYorkUSAWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedGroup77Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedCONTACTMEWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedGroup75Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedProfileWidget53.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedProfileWidget52.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedlisaandersonWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedGroup74Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedBLahblahblahWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedBLahBLahblahblahwritesomethingWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedACTIVITYWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedINTERESTWidget.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedBLahblahblahWidget1.dart';
import 'package:flutterapp/halo2app/generatedprofilewidget51/generated/GeneratedABOUTMEWidget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget51 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 218.0,
                child: GeneratedRectangle2597Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 415.0,
                height: 218.0,
                child: GeneratedImage6Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 28.0,
                child: GeneratedArrow_backWidget4(),
              ),
              Positioned(
                left: 64.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 72.0,
                child: GeneratedProfileWidget52(),
              ),
              Positioned(
                left: 19.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 375.73095703125,
                height: 120.39310455322266,
                child: GeneratedProfileWidget53(),
              ),
              Positioned(
                left: 370.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 34.0,
                child: GeneratedGroup74Widget(),
              ),
              Positioned(
                left: 370.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.46666717529297,
                child: GeneratedGroup77Widget(),
              ),
              Positioned(
                left: 371.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.46666717529297,
                child: GeneratedGroup78Widget(),
              ),
              Positioned(
                left: 369.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.46666717529297,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 371.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.46666717529297,
                child: GeneratedGroup75Widget(),
              ),
              Positioned(
                left: 373.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.46666717529297,
                child: GeneratedGroup8Widget1(),
              ),
              Positioned(
                left: 15.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 30.0,
                child: GeneratedlisaandersonWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 391.0,
                height: 29.0,
                child: GeneratedABOUTMEWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 56.0,
                child: GeneratedBLahBLahblahblahwritesomethingWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 26.0,
                child: GeneratedLOCATIONWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 25.0,
                child: GeneratedACTIVITYWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 25.0,
                child: GeneratedINTERESTWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 25.0,
                child: GeneratedBLahblahblahWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 45.0,
                child: GeneratedNewYorkUSAWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 29.0,
                child: GeneratedCONTACTMEWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 25.0,
                child: GeneratedBLahblahblahWidget1(),
              ),
              Positioned(
                left: -1999.0,
                top: 1966.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 823.0,
                child: GeneratedSearchingWidget2(),
              )
            ]),
      ),
    ));
  }
}
