import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedchatswidget/generated/GeneratedMenuWidget7.dart';
import 'package:flutterapp/halo2app/generatedchatswidget/generated/GeneratedMainContainerWidget.dart';
import 'package:flutterapp/halo2app/generatedchatswidget/generated/GeneratedArrow_backWidget2.dart';
import 'package:flutterapp/halo2app/generatedchatswidget/generated/GeneratedWrapperWidget5.dart';
import 'package:flutterapp/halo2app/generatedchatswidget/generated/GeneratedWrapperWidget7.dart';

/* Frame Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 53.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 39.0,
                child: GeneratedWrapperWidget5(),
              ),
              Positioned(
                left: -2.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 403.0,
                child: GeneratedMainContainerWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 28.0,
                child: GeneratedArrow_backWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 44.0,
                child: GeneratedWrapperWidget7(),
              ),
              Positioned(
                left: 399.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 44.0,
                child: GeneratedMenuWidget7(),
              )
            ]),
      ),
    ));
  }
}
