import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedPeopleWidget1.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget115.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedNature_peopleWidget5.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedVectorWidget454.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedHiLisaAndersonWidget9.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget122.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRectangle1Widget12.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedSendWidget5.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedMenuWidget14.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget120.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget113.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRectangle8Widget7.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget123.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget118.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget116.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedVectorWidget500.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedEllipse2Widget9.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRectangle8Widget6.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedPerson_pinWidget9.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget119.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFilter_listWidget9.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFilter_tilt_shiftWidget18.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedVectorWidget499.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget121.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedMy_locationWidget5.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget117.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedLetsfindyouabuddyWidget9.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedHALCYONWidget11.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedInterestsWidget3.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFilterMatchingWidget.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedProfileWidget66.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget111.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRecord_voice_overWidget8.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRectangle9Widget5.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFilter_tilt_shiftWidget19.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedRectangleWidget11.dart';
import 'package:flutterapp/halo2app/generatedfilterwidget/generated/GeneratedFaceWidget112.dart';

/* Frame Filter
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomePageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 12.0,
                  top: 79.0,
                  right: null,
                  bottom: null,
                  width: 72.0,
                  height: 72.0,
                  child: GeneratedProfileWidget66(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 63.0,
                  child: GeneratedRectangle1Widget12(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.08029197080291971;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 33.0;

                    double percentHeight = 0.027946537059538274;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 23.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.7591240875912408,
                          translateY:
                              constraints.maxHeight * 0.02551640340218712,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget454())
                    ]);
                  }),
                ),
                Positioned(
                  left: 29.0,
                  top: 2.0,
                  right: null,
                  bottom: null,
                  width: 332.0,
                  height: 68.0,
                  child: GeneratedHALCYONWidget11(),
                ),
                Positioned(
                  left: 98.0,
                  top: 82.0,
                  right: null,
                  bottom: null,
                  width: 304.0,
                  height: 35.0,
                  child: GeneratedHiLisaAndersonWidget9(),
                ),
                Positioned(
                  left: -8.0,
                  top: 168.0,
                  right: null,
                  bottom: null,
                  width: 500.0,
                  height: 546.0,
                  child: GeneratedRectangleWidget11(),
                ),
                Positioned(
                  left: 97.0,
                  top: 120.0,
                  right: null,
                  bottom: null,
                  width: 288.0,
                  height: 34.0,
                  child: GeneratedLetsfindyouabuddyWidget9(),
                ),
                Positioned(
                  left: 156.0,
                  top: 725.0,
                  right: null,
                  bottom: null,
                  width: 86.0,
                  height: 84.0,
                  child: GeneratedEllipse2Widget9(),
                ),
                Positioned(
                  left: 225.0,
                  top: 379.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget111(),
                ),
                Positioned(
                  left: 225.0,
                  top: 379.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget112(),
                ),
                Positioned(
                  left: 343.0,
                  top: 276.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget113(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058394160583941604;

                    final double height =
                        constraints.maxHeight * 0.02916160388821385;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.46228710462287104,
                          y: constraints.maxHeight * 0.6452004860267315,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedFaceWidget115(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 48.0,
                  top: 324.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget116(),
                ),
                Positioned(
                  left: 230.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget117(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058394160583941604;

                    final double height =
                        constraints.maxHeight * 0.02916160388821385;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.0681265206812652,
                          y: constraints.maxHeight * 0.27460510328068044,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedFaceWidget118(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 266.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget119(),
                ),
                Positioned(
                  left: 310.0,
                  top: 446.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget120(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058394160583941604;

                    final double height =
                        constraints.maxHeight * 0.02916160388821385;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.5936739659367397,
                          y: constraints.maxHeight * 0.732685297691373,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedFaceWidget121(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 307.0,
                  top: 379.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget122(),
                ),
                Positioned(
                  left: 209.0,
                  top: 422.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget123(),
                ),
                Positioned(
                  left: 174.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 51.0,
                  child: GeneratedRecord_voice_overWidget8(),
                ),
                Positioned(
                  left: 268.0,
                  top: 391.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 45.0,
                  child: GeneratedPerson_pinWidget9(),
                ),
                Positioned(
                  left: 132.0,
                  top: 415.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 43.0,
                  child: GeneratedFilter_tilt_shiftWidget18(),
                ),
                Positioned(
                  left: 349.0,
                  top: 226.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 43.0,
                  child: GeneratedFilter_tilt_shiftWidget19(),
                ),
                Positioned(
                  left: 351.0,
                  top: 94.0,
                  right: null,
                  bottom: null,
                  width: 46.0,
                  height: 45.0,
                  child: GeneratedFilter_listWidget9(),
                ),
                Positioned(
                  left: 22.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 56.0,
                  height: 53.0,
                  child: GeneratedNature_peopleWidget5(),
                ),
                Positioned(
                  left: 349.0,
                  top: 649.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 51.0,
                  child: GeneratedMy_locationWidget5(),
                ),
                Positioned(
                  left: 336.0,
                  top: 747.0,
                  right: null,
                  bottom: null,
                  width: 47.0,
                  height: 46.0,
                  child: GeneratedSendWidget5(),
                ),
                Positioned(
                  left: 7.0,
                  top: 6.0,
                  right: null,
                  bottom: null,
                  width: 45.0,
                  height: 49.0,
                  child: GeneratedMenuWidget14(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.0535279805352798;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 22.0;

                    double percentHeight = 0.038882138517618466;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 32.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.8929440389294404,
                          translateY:
                              constraints.maxHeight * 0.019441069258809233,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget499())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedRectangle7Widget5(),
                ),
                Positioned(
                  left: -4.0,
                  top: 613.0,
                  right: null,
                  bottom: null,
                  width: 419.0,
                  height: 233.0,
                  child: GeneratedRectangle8Widget6(),
                ),
                Positioned(
                  left: 34.0,
                  top: 444.0,
                  right: null,
                  bottom: null,
                  width: 87.0,
                  height: 36.0,
                  child: GeneratedRectangle9Widget5(),
                ),
                Positioned(
                  left: 78.0,
                  top: 627.0,
                  right: null,
                  bottom: null,
                  width: 246.0,
                  height: 51.0,
                  child: GeneratedFilterMatchingWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.1386861313868613;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 57.0;

                    double percentHeight = 0.07290400972053462;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 60.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.20437956204379562,
                          translateY:
                              constraints.maxHeight * 0.8444714459295262,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget500())
                    ]);
                  }),
                ),
                Positioned(
                  left: 80.0,
                  top: 770.0,
                  right: null,
                  bottom: null,
                  width: 69.0,
                  height: 31.0,
                  child: GeneratedPeopleWidget1(),
                ),
                Positioned(
                  left: 251.0,
                  top: 769.0,
                  right: null,
                  bottom: null,
                  width: 86.0,
                  height: 31.0,
                  child: GeneratedInterestsWidget3(),
                ),
                Positioned(
                  left: 264.0,
                  top: 690.0,
                  right: null,
                  bottom: null,
                  width: 51.0,
                  height: 70.0,
                  child: GeneratedRectangle8Widget7(),
                )
              ]),
        ),
      ),
    ));
  }
}
