import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_1widget/generated/GeneratedGooglePixel2XL7Widget2.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_1widget/generated/GeneratedLine5Widget2.dart';

/* Frame Filter_Interests_1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilter_Interests_1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedGooglePixel2XL7Widget2(),
                ),
                Positioned(
                  left: 191.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 4.0,
                  child: GeneratedLine5Widget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
