import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedVector36Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse26Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse25Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse32Widget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedGroup458Widget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedInterestWidget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/Generated20Widget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedAgeWidget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedAthaliaPutriWidget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse27Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse24Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedIs6KmAwayWidget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse29Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/Generateda_putriWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse30Widget1.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedFrame3294Widget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedEllipse33Widget.dart';
import 'package:flutterapp/halo2app/generatedbuddymilgyawidget/generated/GeneratedRectangle2611Widget.dart';

/* Frame Buddy Milgya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBuddyMilgyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 20.0,
                child: GeneratedVector36Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 54.0,
                child: GeneratedButtonWidget1(),
              ),
              Positioned(
                left: 124.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 10.594594955444336,
                height: 10.606060981750488,
                child: GeneratedEllipse24Widget1(),
              ),
              Positioned(
                left: 99.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 35.0,
                child: GeneratedAthaliaPutriWidget(),
              ),
              Positioned(
                left: 94.7568359375,
                top: 204.939453125,
                right: null,
                bottom: null,
                width: 4.54054069519043,
                height: 4.545454502105713,
                child: GeneratedEllipse30Widget1(),
              ),
              Positioned(
                left: 304.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 4.54054069519043,
                height: 4.545454502105713,
                child: GeneratedEllipse33Widget(),
              ),
              Positioned(
                left: 335.4052734375,
                top: 61.0,
                right: null,
                bottom: null,
                width: 10.594594955444336,
                height: 10.606060981750488,
                child: GeneratedEllipse32Widget(),
              ),
              Positioned(
                left: 283.946044921875,
                top: 92.818115234375,
                right: null,
                bottom: null,
                width: 6.054054260253906,
                height: 6.060606002807617,
                child: GeneratedEllipse27Widget1(),
              ),
              Positioned(
                left: 309.67578125,
                top: 130.697021484375,
                right: null,
                bottom: null,
                width: 10.594594955444336,
                height: 10.606060981750488,
                child: GeneratedEllipse25Widget1(),
              ),
              Positioned(
                left: 203.729736328125,
                top: 71.6060791015625,
                right: null,
                bottom: null,
                width: 7.567567348480225,
                height: 7.5757575035095215,
                child: GeneratedEllipse29Widget1(),
              ),
              Positioned(
                left: 66.0,
                top: 162.51513671875,
                right: null,
                bottom: null,
                width: 7.567567348480225,
                height: 7.5757575035095215,
                child: GeneratedEllipse26Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 29.0,
                child: GeneratedInterestWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 38.0,
                child: GeneratedIs6KmAwayWidget(),
              ),
              Positioned(
                left: 182.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 44.0,
                child: Generated20Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 43.0,
                child: Generateda_putriWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 54.0,
                child: GeneratedButtonWidget2(),
              ),
              Positioned(
                left: 60.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 37.0,
                child: GeneratedRectangle2611Widget(),
              ),
              Positioned(
                left: 99.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 30.0,
                child: GeneratedAgeWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 37.0,
                child: GeneratedGroup458Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3819951338199513;

                  final double height =
                      constraints.maxHeight * 0.19805589307411908;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.32116788321167883,
                        y: constraints.maxHeight * 0.12879708383961117,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame3294Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 310.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 43.0,
                child: GeneratedImage10Widget(),
              )
            ]),
      ),
    ));
  }
}
