import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedGroup73Widget.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedGroup72Widget.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedOngoingActivitiesWidget1.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedIconaddWidget.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedVectorWidget96.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedArrow_backWidget.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/halo2app/generatedongoingactivitieswidget/generated/GeneratedGroup71Widget.dart';

/* Frame Ongoing Activities
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOngoingActivitiesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 40.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 65.0,
                child: GeneratedOngoingActivitiesWidget1(),
              ),
              Positioned(
                left: null,
                top: 17.0,
                right: 15.735294342041016,
                bottom: null,
                width: 36.264705657958984,
                height: 33.0,
                child: GeneratedIconaddWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 28.0,
                child: GeneratedArrow_backWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 51.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07785888077858881;
                  double scaleX = (constraints.maxWidth * percentWidth) / 32.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.09002433090024331,
                        translateY: constraints.maxHeight * 0.11543134872417983,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget96())
                  ]);
                }),
              ),
              Positioned(
                left: 19.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 101.0,
                child: GeneratedGroup69Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 101.0,
                child: GeneratedGroup73Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 101.0,
                child: GeneratedGroup72Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 101.0,
                child: GeneratedGroup71Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 101.0,
                child: GeneratedGroup70Widget(),
              )
            ]),
      ),
    ));
  }
}
