import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_3widget/generated/GeneratedMenucells_whiteWidget1.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_3widget/generated/GeneratedMenucells_whiteWidget.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_3widget/generated/GeneratedGooglePixel2XL7Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_3widget/generated/GeneratedLine5Widget.dart';

/* Frame Filter_Interests_3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilter_Interests_3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFilterWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedGooglePixel2XL7Widget(),
                ),
                Positioned(
                  left: 191.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 4.0,
                  child: GeneratedLine5Widget(),
                ),
                Positioned(
                  left: 131.0,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 266.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 82.50,
                      z: 0,
                      child: GeneratedMenucells_whiteWidget()),
                ),
                Positioned(
                  left: 142.0,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 241.22775268554688,
                  height: 36.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 129.50,
                      z: 0,
                      child: GeneratedMenucells_whiteWidget1()),
                )
              ]),
        ),
      ),
    ));
  }
}
