import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedSearchingWidget1.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/halo2app/generatedsearchingwidget/generated/GeneratedHALCYONWidget.dart';

/* Frame Searching
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -29.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 470.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 68.0,
                child: GeneratedHALCYONWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09732360097323602;
                  double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                  double percentHeight = 0.03402187120291616;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 28.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7420924574209246,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 9.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0535279805352798;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8929440389294404,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2())
                  ]);
                }),
              ),
              Positioned(
                left: 47.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 117.0,
                child: GeneratedSearchingWidget1(),
              ),
              Positioned(
                left: 67.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedSearchWidget(),
              )
            ]),
      ),
    ));
  }
}
