import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedchat_ui_2widget/generated/GeneratedWrapperWidget3.dart';
import 'package:flutterapp/halo2app/generatedchat_ui_2widget/generated/GeneratedFrame3268Widget.dart';
import 'package:flutterapp/halo2app/generatedchat_ui_2widget/generated/GeneratedChatAreaWidget.dart';

/* Frame Chat_ui_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat_ui_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 12.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 30.0,
                child: GeneratedWrapperWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9294403892944039;

                  final double height =
                      constraints.maxHeight * 0.06804374240583232;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0413625304136253,
                        y: constraints.maxHeight * 0.9040097205346294,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame3268Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 667.0,
                child: GeneratedChatAreaWidget(),
              )
            ]),
      ),
    ));
  }
}
