import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfilter_peoplewidget/generated/GeneratedGooglePixel2XL7Widget3.dart';
import 'package:flutterapp/halo2app/generatedfilter_peoplewidget/generated/GeneratedLine5Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedfilter_peoplewidget/generated/GeneratedVectorWidget405.dart';
import 'package:flutterapp/halo2app/generatedfilter_peoplewidget/generated/GeneratedSliderWidget.dart';

/* Frame Filter_People
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilter_PeopleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFilterWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedGooglePixel2XL7Widget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.1386861313868613;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 57.0;

                    double percentHeight = 0.07290400972053462;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 60.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.17518248175182483,
                          translateY:
                              constraints.maxHeight * 0.46051032806804376,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget405())
                    ]);
                  }),
                ),
                Positioned(
                  left: 191.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 4.0,
                  child: GeneratedLine5Widget3(),
                ),
                Positioned(
                  left: 34.0,
                  top: 503.0,
                  right: null,
                  bottom: null,
                  width: 343.0,
                  height: 28.0,
                  child: GeneratedSliderWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
