import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedVectorWidget211.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedVectorWidget210.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedPrivacySecurityWidget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedVectorWidget214.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedApplicationWidget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedVectorWidget212.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedVectorWidget209.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedAboutWidget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedIcons8about301Widget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedAccountWidget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedVectorWidget213.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/halo2app/generatedsettingswidget/generated/GeneratedNotificationsWidget.dart';

/* Frame Settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 51.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07785888077858881;
                  double scaleX = (constraints.maxWidth * percentWidth) / 32.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.11678832116788321,
                        translateY: constraints.maxHeight * 0.1117861482381531,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget209())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 1.0,
                child: GeneratedLine18Widget(),
              ),
              Positioned(
                left: 109.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 59.0,
                child: GeneratedAccountWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 56.0,
                child: GeneratedPrivacySecurityWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 59.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 59.0,
                child: GeneratedApplicationWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 59.0,
                child: GeneratedAboutWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07785888077858881;
                  double scaleX = (constraints.maxWidth * percentWidth) / 32.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.09002433090024331,
                        translateY: constraints.maxHeight * 0.24665856622114216,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget210())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0705596107055961;
                  double scaleX = (constraints.maxWidth * percentWidth) / 29.0;

                  double percentHeight = 0.041312272174969626;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 34.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.09732360097323602,
                        translateY: constraints.maxHeight * 0.4264884568651276,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget211())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0705596107055961;
                  double scaleX = (constraints.maxWidth * percentWidth) / 29.0;

                  double percentHeight = 0.046172539489671933;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 38.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.09732360097323602,
                        translateY: constraints.maxHeight * 0.330498177399757,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget212())
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 54.0,
                child: GeneratedButtonWidget5(),
              ),
              Positioned(
                left: 32.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedIcons8about301Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.072992700729927;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.09002433090024331,
                        translateY: constraints.maxHeight * 0.5224787363304981,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget213())
                  ]);
                }),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 70.0,
                top: -4.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 72.0,
                child: GeneratedSettingsWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07623682230928519;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 31.33333396911621;

                  double percentHeight = 0.022681244378536036;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      18.666664123535156;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.051094890510948905,
                        translateY: constraints.maxHeight * 0.02551640340218712,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget214())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
