import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedPerson_addWidget3.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedPerson_addWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedJarrodParkesWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedShuangLiuWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedMelissaHuiWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedFindABuddyWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedPerson_addWidget2.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedRectangle1Widget13.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedVectorWidget503.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedBioWidget2.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedPerson_addWidget4.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedEllipse5Widget12.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedGabrielRuttnerWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedBioWidget1.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedMichaelDendrikWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedArrow_backWidget5.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedPerson_addWidget1.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedBioWidget3.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedLine5Widget4.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedBioWidget.dart';
import 'package:flutterapp/halo2app/generatedfindabuddywidget/generated/GeneratedBioWidget4.dart';

/* Frame Find A buddy
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFindAbuddyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle1Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 28.0,
                child: GeneratedArrow_backWidget5(),
              ),
              Positioned(
                left: 40.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 65.0,
                child: GeneratedFindABuddyWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 85.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 91.0,
                child: GeneratedEllipse5Widget12(),
              ),
              Positioned(
                left: 20.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 91.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 91.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 91.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 247.0020294189453,
                height: 0.5,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 247.0020294189453,
                height: 0.5,
                child: GeneratedLine5Widget4(),
              ),
              Positioned(
                left: 127.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 247.0020294189453,
                height: 0.5,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 247.0020294189453,
                height: 0.5,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 247.0020294189453,
                height: 0.5,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 51.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07785888077858881;
                  double scaleX = (constraints.maxWidth * percentWidth) / 32.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07785888077858881,
                        translateY: constraints.maxHeight * 0.12150668286755771,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget503())
                  ]);
                }),
              ),
              Positioned(
                left: 135.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 38.0,
                child: GeneratedShuangLiuWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 38.0,
                child: GeneratedMelissaHuiWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 38.0,
                child: GeneratedJarrodParkesWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 38.0,
                child: GeneratedGabrielRuttnerWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 38.0,
                child: GeneratedMichaelDendrikWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 39.0,
                child: GeneratedBioWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 39.0,
                child: GeneratedBioWidget1(),
              ),
              Positioned(
                left: 135.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 39.0,
                child: GeneratedBioWidget2(),
              ),
              Positioned(
                left: 135.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 39.0,
                child: GeneratedBioWidget3(),
              ),
              Positioned(
                left: 135.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 39.0,
                child: GeneratedBioWidget4(),
              ),
              Positioned(
                left: 341.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_addWidget(),
              ),
              Positioned(
                left: 343.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_addWidget1(),
              ),
              Positioned(
                left: 343.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_addWidget2(),
              ),
              Positioned(
                left: 344.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_addWidget3(),
              ),
              Positioned(
                left: 345.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_addWidget4(),
              )
            ]),
      ),
    ));
  }
}
