import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedchat_uiwidget/generated/GeneratedChatAreaWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedchat_uiwidget/generated/GeneratedWrapperWidget4.dart';
import 'package:flutterapp/halo2app/generatedchat_uiwidget/generated/GeneratedGBoardAlphabeticWidget.dart';
import 'package:flutterapp/halo2app/generatedchat_uiwidget/generated/GeneratedFrame3268Widget1.dart';

/* Frame Chat_ui
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat_uiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 12.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 30.0,
                child: GeneratedWrapperWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 444.0,
                child: GeneratedChatAreaWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0048661800486618;

                  final double height =
                      constraints.maxHeight * 0.06804374240583232;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.004866180048661801,
                        y: constraints.maxHeight * 0.5795868772782503,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame3268Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -2.0,
                top: null,
                right: null,
                bottom: 2.0,
                width: 414.0,
                height: 288.0,
                child: GeneratedGBoardAlphabeticWidget(),
              )
            ]),
      ),
    ));
  }
}
