import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedbuddieslistwidget/generated/GeneratedArrow_backWidget1.dart';
import 'package:flutterapp/halo2app/generatedbuddieslistwidget/generated/GeneratedWrapperWidget2.dart';
import 'package:flutterapp/halo2app/generatedbuddieslistwidget/generated/GeneratedWrapperWidget.dart';
import 'package:flutterapp/halo2app/generatedbuddieslistwidget/generated/GeneratedContactListWidget.dart';

/* Frame Buddies list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBuddieslistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 62.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 30.0,
                child: GeneratedWrapperWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 605.0,
                child: GeneratedContactListWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 44.0,
                child: GeneratedWrapperWidget2(),
              ),
              Positioned(
                left: 3.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 28.0,
                child: GeneratedArrow_backWidget1(),
              )
            ]),
      ),
    ));
  }
}
