import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generateddostmilgyawidget/generated/GeneratedItstimetohavefunnowWidget.dart';
import 'package:flutterapp/halo2app/generateddostmilgyawidget/generated/GeneratedYouvefoundanewbuddyWidget.dart';
import 'package:flutterapp/halo2app/generateddostmilgyawidget/generated/GeneratedGroup457Widget.dart';
import 'package:flutterapp/halo2app/generateddostmilgyawidget/generated/GeneratedVector36Widget.dart';
import 'package:flutterapp/halo2app/generateddostmilgyawidget/generated/GeneratedButtonWidget.dart';

/* Frame Dost Milgya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDostMilgyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 20.0,
                child: GeneratedVector36Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 68.0,
                child: GeneratedYouvefoundanewbuddyWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 51.0,
                child: GeneratedItstimetohavefunnowWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 54.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 252.0,
                child: GeneratedGroup457Widget(),
              )
            ]),
      ),
    ));
  }
}
