import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedhelpdesk25widget/generated/GeneratedImage11Widget.dart';
import 'package:flutterapp/halo2app/generatedhelpdesk25widget/generated/GeneratedRectangle2599Widget.dart';
import 'package:flutterapp/halo2app/generatedhelpdesk25widget/generated/GeneratedReachoutforhelpWidget.dart';
import 'package:flutterapp/halo2app/generatedhelpdesk25widget/generated/GeneratedContactUshalcyongmailcomPhoneNo1234567890Widget.dart';
import 'package:flutterapp/halo2app/generatedhelpdesk25widget/generated/GeneratedRectangle2598Widget.dart';
import 'package:flutterapp/halo2app/generatedhelpdesk25widget/generated/GeneratedReachoutusincaseyouneedanyhelpinunderstandingtheappfunc.dart';

/* Frame Help Desk - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHelpDesk25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 64.0,
                child: GeneratedRectangle2598Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 212.0,
                child: GeneratedRectangle2599Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 162.0,
                child:
                    GeneratedReachoutusincaseyouneedanyhelpinunderstandingtheappfunc(),
              ),
              Positioned(
                left: 0.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 59.0,
                child: GeneratedReachoutforhelpWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 76.0,
                child:
                    GeneratedContactUshalcyongmailcomPhoneNo1234567890Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 418.0,
                height: 159.0,
                child: GeneratedImage11Widget(),
              )
            ]),
      ),
    ));
  }
}
