import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_2widget/generated/GeneratedMenucells_whiteWidget2.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_2widget/generated/GeneratedGooglePixel2XL7Widget1.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_2widget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/halo2app/generatedfilter_interests_2widget/generated/GeneratedFrame3314Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Filter_Interests_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilter_Interests_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFilterWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedGooglePixel2XL7Widget1(),
                ),
                Positioned(
                  left: 191.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 4.0,
                  child: GeneratedLine5Widget1(),
                ),
                Positioned(
                  left: 145.0,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 241.22775268554688,
                  height: 17.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 295.00,
                      z: 0,
                      child: GeneratedMenucells_whiteWidget2()),
                ),
                Positioned(
                  left: 131.0,
                  top: 475.0,
                  right: null,
                  bottom: null,
                  width: 266.0,
                  height: 225.0,
                  child: GeneratedFrame3314Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
