import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedProfileWidget22.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget31.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedVectorWidget139.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedHALCYONWidget3.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget35.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedVectorWidget133.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedVectorWidget134.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFilter_tilt_shiftWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget33.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedPerson_pinWidget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget34.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFilter_tilt_shiftWidget5.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedVectorWidget131.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget37.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget38.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget32.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedVectorWidget135.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedEllipse9Widget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget30.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedLetsfindyouabuddyWidget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget36.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedHiLisaAndersonWidget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget28.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedProfileWidget24.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedMenuWidget3.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget27.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFaceWidget26.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedRectangleWidget3.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedRecord_voice_overWidget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/halo2app/generatedevent_2widget/generated/GeneratedFilter_listWidget2.dart';

/* Frame Event_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEvent_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 33.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 68.0,
                child: GeneratedHALCYONWidget3(),
              ),
              Positioned(
                left: 98.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 35.0,
                child: GeneratedHiLisaAndersonWidget2(),
              ),
              Positioned(
                left: -7.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 467.0,
                height: 659.0,
                child: GeneratedRectangleWidget3(),
              ),
              Positioned(
                left: 258.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 108.0,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 34.0,
                child: GeneratedLetsfindyouabuddyWidget2(),
              ),
              Positioned(
                left: 225.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget26(),
              ),
              Positioned(
                left: 225.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget27(),
              ),
              Positioned(
                left: 343.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.46228710462287104,
                        y: constraints.maxHeight * 0.6452004860267315,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget30(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 48.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget31(),
              ),
              Positioned(
                left: 230.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget32(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0681265206812652,
                        y: constraints.maxHeight * 0.27460510328068044,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget33(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 266.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget34(),
              ),
              Positioned(
                left: 310.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget35(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5936739659367397,
                        y: constraints.maxHeight * 0.732685297691373,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget36(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 307.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget37(),
              ),
              Positioned(
                left: 203.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget38(),
              ),
              Positioned(
                left: 252.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 45.0,
                child: GeneratedPerson_pinWidget2(),
              ),
              Positioned(
                left: 132.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedFilter_tilt_shiftWidget4(),
              ),
              Positioned(
                left: 349.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedFilter_tilt_shiftWidget5(),
              ),
              Positioned(
                left: 351.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 45.0,
                child: GeneratedFilter_listWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09732360097323602;
                  double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                  double percentHeight = 0.03402187120291616;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 28.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7420924574209246,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget131())
                  ]);
                }),
              ),
              Positioned(
                left: 9.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedMenuWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0535279805352798;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8929440389294404,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget133())
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 709.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle10Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10006081796910642;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      41.124996185302734;

                  double percentHeight = 0.04191980558930741;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 34.5;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7493917274939172,
                        translateY: constraints.maxHeight * 0.9003645200486027,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget134())
                  ]);
                }),
              ),
              Positioned(
                left: 163.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 69.0,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1145093226374791;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      47.063331604003906;

                  double percentHeight = 0.05320929785690215;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      43.79125213623047;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.11192214111922141,
                        translateY: constraints.maxHeight * 0.8918590522478737,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget135())
                  ]);
                }),
              ),
              Positioned(
                left: 179.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 51.0,
                child: GeneratedRecord_voice_overWidget2(),
              ),
              Positioned(
                left: 327.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 62.0,
                child: GeneratedEllipse9Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10705595178905775;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      43.999996185302734;

                  double percentHeight = 0.054576748631269933;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      44.916664123535156;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8150851581508516,
                        translateY: constraints.maxHeight * 0.7812879708383961,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget139())
                  ]);
                }),
              ),
              Positioned(
                left: 489.0,
                top: -893.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 72.0,
                child: GeneratedProfileWidget22(),
              ),
              Positioned(
                left: 12.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 72.0,
                child: GeneratedProfileWidget24(),
              )
            ]),
      ),
    ));
  }
}
