import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRecord_voice_overWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget9.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFasolidsearchWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget1.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedMenuWidget1.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFilter_listWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedIllustrationHangoutWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedHALCYONWidget1.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget2.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedHiLisaAndersonWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget6.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedVectorWidget43.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget5.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangle2611Widget2.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedLetsfindyouabuddyWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangleWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangle2610Widget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedVectorWidget40.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget12.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedVectorWidget44.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFilter_tilt_shiftWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedVectorWidget42.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget11.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget4.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedIllustrationSearchingLookingWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFilter_tilt_shiftWidget1.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget10.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedVectorWidget48.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget8.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedFaceWidget7.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedCreateWidget.dart';
import 'package:flutterapp/halo2app/generatedmiddlebuttonwidget/generated/GeneratedPerson_pinWidget.dart';

/* Frame  Middle Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMiddleButtonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: -4.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 233.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 68.0,
                child: GeneratedHALCYONWidget1(),
              ),
              Positioned(
                left: 98.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 35.0,
                child: GeneratedHiLisaAndersonWidget(),
              ),
              Positioned(
                left: -7.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 467.0,
                height: 659.0,
                child: GeneratedRectangleWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 34.0,
                child: GeneratedLetsfindyouabuddyWidget(),
              ),
              Positioned(
                left: 225.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget(),
              ),
              Positioned(
                left: 225.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget1(),
              ),
              Positioned(
                left: 343.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.46228710462287104,
                        y: constraints.maxHeight * 0.6452004860267315,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 48.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget5(),
              ),
              Positioned(
                left: 230.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0681265206812652,
                        y: constraints.maxHeight * 0.27460510328068044,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 266.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget8(),
              ),
              Positioned(
                left: 310.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5936739659367397,
                        y: constraints.maxHeight * 0.732685297691373,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 307.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget11(),
              ),
              Positioned(
                left: 203.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget12(),
              ),
              Positioned(
                left: 252.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 45.0,
                child: GeneratedPerson_pinWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedFilter_tilt_shiftWidget(),
              ),
              Positioned(
                left: 349.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedFilter_tilt_shiftWidget1(),
              ),
              Positioned(
                left: 351.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 45.0,
                child: GeneratedFilter_listWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09732360097323602;
                  double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                  double percentHeight = 0.03402187120291616;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 28.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7420924574209246,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget40())
                  ]);
                }),
              ),
              Positioned(
                left: 9.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedMenuWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0535279805352798;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8929440389294404,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget42())
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 709.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10006081796910642;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      41.124996185302734;

                  double percentHeight = 0.04191980558930741;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 34.5;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7493917274939172,
                        translateY: constraints.maxHeight * 0.9003645200486027,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget43())
                  ]);
                }),
              ),
              Positioned(
                left: 163.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 69.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1145093226374791;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      47.063331604003906;

                  double percentHeight = 0.05320929785690215;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      43.79125213623047;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.11192214111922141,
                        translateY: constraints.maxHeight * 0.8918590522478737,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget44())
                  ]);
                }),
              ),
              Positioned(
                left: 327.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 62.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 51.0,
                child: GeneratedRecord_voice_overWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10705595178905775;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      43.999996185302734;

                  double percentHeight = 0.054576748631269933;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      44.916664123535156;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8150851581508516,
                        translateY: constraints.maxHeight * 0.7812879708383961,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget48())
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 72.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 823.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 248.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 118.0,
                child: GeneratedRectangle2610Widget(),
              ),
              Positioned(
                left: -4.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 233.0,
                child: GeneratedRectangle2611Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 53.0,
                child: GeneratedCreateWidget(),
              ),
              Positioned(
                left: 238.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 60.0,
                child: GeneratedSearchWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2944038929440389;

                  final double height =
                      constraints.maxHeight * 0.15552855407047386;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5888077858880778,
                        y: constraints.maxHeight * 0.7752126366950183,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIllustrationSearchingLookingWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2944038929440389;

                  final double height =
                      constraints.maxHeight * 0.15552855407047386;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09002433090024331,
                        y: constraints.maxHeight * 0.778857837181045,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIllustrationHangoutWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 260.0,
                top: 659.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 81.0,
                child: GeneratedFasolidsearchWidget(),
              )
            ]),
      ),
    ));
  }
}
