import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget160.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget154.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget162.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedVectorWidget645.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget158.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedVectorWidget646.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFilter_listWidget12.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedMenuWidget17.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedRectangleWidget14.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget152.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedEllipse2Widget12.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFilter_tilt_shiftWidget24.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget157.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedEllipse9Widget6.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedLetsfindyouabuddyWidget12.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedRecord_voice_overWidget11.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedVectorWidget650.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedVectorWidget642.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedRectangle10Widget9.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedPerson_pinWidget12.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFilter_tilt_shiftWidget25.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget151.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedProfileWidget74.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget161.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedRectangle1Widget16.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedHiLisaAndersonWidget12.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedHALCYONWidget14.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget159.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedVectorWidget644.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget150.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget155.dart';
import 'package:flutterapp/halo2app/generatedhomepagewidget/generated/GeneratedFaceWidget156.dart';

/* Frame  Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 63.0,
                child: GeneratedRectangle1Widget16(),
              ),
              Positioned(
                left: 33.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 68.0,
                child: GeneratedHALCYONWidget14(),
              ),
              Positioned(
                left: 98.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 35.0,
                child: GeneratedHiLisaAndersonWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 659.0,
                child: GeneratedRectangleWidget14(),
              ),
              Positioned(
                left: 97.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 34.0,
                child: GeneratedLetsfindyouabuddyWidget12(),
              ),
              Positioned(
                left: 225.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget150(),
              ),
              Positioned(
                left: 225.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget151(),
              ),
              Positioned(
                left: 343.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget152(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.46228710462287104,
                        y: constraints.maxHeight * 0.6452004860267315,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget154(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 48.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget155(),
              ),
              Positioned(
                left: 230.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget156(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0681265206812652,
                        y: constraints.maxHeight * 0.27460510328068044,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget157(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 266.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget158(),
              ),
              Positioned(
                left: 310.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget159(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058394160583941604;

                  final double height =
                      constraints.maxHeight * 0.02916160388821385;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5936739659367397,
                        y: constraints.maxHeight * 0.732685297691373,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFaceWidget160(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 307.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget161(),
              ),
              Positioned(
                left: 203.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFaceWidget162(),
              ),
              Positioned(
                left: 252.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 45.0,
                child: GeneratedPerson_pinWidget12(),
              ),
              Positioned(
                left: 98.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedFilter_tilt_shiftWidget24(),
              ),
              Positioned(
                left: 349.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedFilter_tilt_shiftWidget25(),
              ),
              Positioned(
                left: 351.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 45.0,
                child: GeneratedFilter_listWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08029197080291971;
                  double scaleX = (constraints.maxWidth * percentWidth) / 33.0;

                  double percentHeight = 0.027946537059538274;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 23.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7591240875912408,
                        translateY: constraints.maxHeight * 0.02551640340218712,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget642())
                  ]);
                }),
              ),
              Positioned(
                left: 9.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedMenuWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0535279805352798;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.038882138517618466;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8929440389294404,
                        translateY:
                            constraints.maxHeight * 0.019441069258809233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget644())
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle10Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10006081796910642;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      41.124996185302734;

                  double percentHeight = 0.04191980558930741;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 34.5;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7493917274939172,
                        translateY: constraints.maxHeight * 0.9003645200486027,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget645())
                  ]);
                }),
              ),
              Positioned(
                left: 163.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 69.0,
                child: GeneratedEllipse2Widget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1145093226374791;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      47.063331604003906;

                  double percentHeight = 0.05320929785690215;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      43.79125213623047;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.11192214111922141,
                        translateY: constraints.maxHeight * 0.8918590522478737,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget646())
                  ]);
                }),
              ),
              Positioned(
                left: 327.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 62.0,
                child: GeneratedEllipse9Widget6(),
              ),
              Positioned(
                left: 179.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 51.0,
                child: GeneratedRecord_voice_overWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10705595178905775;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      43.999996185302734;

                  double percentHeight = 0.054576748631269933;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      44.916664123535156;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8150851581508516,
                        translateY: constraints.maxHeight * 0.7812879708383961,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget650())
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 72.0,
                child: GeneratedProfileWidget74(),
              )
            ]),
      ),
    ));
  }
}
