import 'package:flutter/material.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFilter_tilt_shiftWidget17.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget109.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRoomWidget.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFilter_listWidget8.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget103.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedVectorWidget406.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRectangle9Widget4.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedPerson_pinWidget8.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget108.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget100.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedMenuWidget13.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRectangle1Widget11.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget105.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedHALCYONWidget10.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget99.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRecord_voice_overWidget7.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRectangleWidget10.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget104.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget107.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedEllipse2Widget8.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedAreaWidget.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedMy_locationWidget4.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedRectangle8Widget5.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget106.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedProfileWidget64.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedSendWidget4.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedLetsfindyouabuddyWidget8.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget110.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget98.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedLocationWidget1.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedVectorWidget451.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFaceWidget102.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedFilter_tilt_shiftWidget16.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedNature_peopleWidget4.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedHiLisaAndersonWidget8.dart';
import 'package:flutterapp/halo2app/generatedfilter_locationwidget/generated/GeneratedLine6Widget.dart';

/* Frame Filter_location
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilter_locationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 11.0,
                  top: 79.0,
                  right: null,
                  bottom: null,
                  width: 72.0,
                  height: 72.0,
                  child: GeneratedProfileWidget64(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 63.0,
                  child: GeneratedRectangle1Widget11(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.08029197080291971;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 33.0;

                    double percentHeight = 0.027946537059538274;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 23.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.7591240875912408,
                          translateY:
                              constraints.maxHeight * 0.02551640340218712,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget406())
                    ]);
                  }),
                ),
                Positioned(
                  left: 29.0,
                  top: 2.0,
                  right: null,
                  bottom: null,
                  width: 332.0,
                  height: 68.0,
                  child: GeneratedHALCYONWidget10(),
                ),
                Positioned(
                  left: 98.0,
                  top: 82.0,
                  right: null,
                  bottom: null,
                  width: 304.0,
                  height: 35.0,
                  child: GeneratedHiLisaAndersonWidget8(),
                ),
                Positioned(
                  left: -8.0,
                  top: 168.0,
                  right: null,
                  bottom: null,
                  width: 500.0,
                  height: 546.0,
                  child: GeneratedRectangleWidget10(),
                ),
                Positioned(
                  left: 97.0,
                  top: 120.0,
                  right: null,
                  bottom: null,
                  width: 288.0,
                  height: 34.0,
                  child: GeneratedLetsfindyouabuddyWidget8(),
                ),
                Positioned(
                  left: 156.0,
                  top: 725.0,
                  right: null,
                  bottom: null,
                  width: 86.0,
                  height: 84.0,
                  child: GeneratedEllipse2Widget8(),
                ),
                Positioned(
                  left: 225.0,
                  top: 379.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget98(),
                ),
                Positioned(
                  left: 225.0,
                  top: 379.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget99(),
                ),
                Positioned(
                  left: 343.0,
                  top: 276.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget100(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058394160583941604;

                    final double height =
                        constraints.maxHeight * 0.02916160388821385;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.46228710462287104,
                          y: constraints.maxHeight * 0.6452004860267315,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedFaceWidget102(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 48.0,
                  top: 324.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget103(),
                ),
                Positioned(
                  left: 230.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget104(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058394160583941604;

                    final double height =
                        constraints.maxHeight * 0.02916160388821385;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.0681265206812652,
                          y: constraints.maxHeight * 0.27460510328068044,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedFaceWidget105(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 266.0,
                  top: 367.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget106(),
                ),
                Positioned(
                  left: 310.0,
                  top: 446.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget107(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058394160583941604;

                    final double height =
                        constraints.maxHeight * 0.02916160388821385;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.5936739659367397,
                          y: constraints.maxHeight * 0.732685297691373,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedFaceWidget108(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 307.0,
                  top: 379.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget109(),
                ),
                Positioned(
                  left: 209.0,
                  top: 422.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFaceWidget110(),
                ),
                Positioned(
                  left: 174.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 51.0,
                  child: GeneratedRecord_voice_overWidget7(),
                ),
                Positioned(
                  left: 268.0,
                  top: 391.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 45.0,
                  child: GeneratedPerson_pinWidget8(),
                ),
                Positioned(
                  left: 132.0,
                  top: 415.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 43.0,
                  child: GeneratedFilter_tilt_shiftWidget16(),
                ),
                Positioned(
                  left: 349.0,
                  top: 226.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 43.0,
                  child: GeneratedFilter_tilt_shiftWidget17(),
                ),
                Positioned(
                  left: 351.0,
                  top: 94.0,
                  right: null,
                  bottom: null,
                  width: 46.0,
                  height: 45.0,
                  child: GeneratedFilter_listWidget8(),
                ),
                Positioned(
                  left: 22.0,
                  top: 740.0,
                  right: null,
                  bottom: null,
                  width: 56.0,
                  height: 53.0,
                  child: GeneratedNature_peopleWidget4(),
                ),
                Positioned(
                  left: 349.0,
                  top: 649.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 51.0,
                  child: GeneratedMy_locationWidget4(),
                ),
                Positioned(
                  left: 336.0,
                  top: 747.0,
                  right: null,
                  bottom: null,
                  width: 47.0,
                  height: 46.0,
                  child: GeneratedSendWidget4(),
                ),
                Positioned(
                  left: 7.0,
                  top: 6.0,
                  right: null,
                  bottom: null,
                  width: 45.0,
                  height: 49.0,
                  child: GeneratedMenuWidget13(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.0535279805352798;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 22.0;

                    double percentHeight = 0.038882138517618466;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 32.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.8929440389294404,
                          translateY:
                              constraints.maxHeight * 0.019441069258809233,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget451())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 3.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedRectangle7Widget4(),
                ),
                Positioned(
                  left: -8.0,
                  top: 350.0,
                  right: null,
                  bottom: null,
                  width: 419.0,
                  height: 499.0,
                  child: GeneratedRectangle8Widget5(),
                ),
                Positioned(
                  left: 34.0,
                  top: 444.0,
                  right: null,
                  bottom: null,
                  width: 87.0,
                  height: 36.0,
                  child: GeneratedRectangle9Widget4(),
                ),
                Positioned(
                  left: 129.0,
                  top: 384.0,
                  right: null,
                  bottom: null,
                  width: 207.0,
                  height: 51.0,
                  child: GeneratedLocationWidget1(),
                ),
                Positioned(
                  left: 76.0,
                  top: 382.0,
                  right: null,
                  bottom: null,
                  width: 44.0,
                  height: 52.0,
                  child: GeneratedRoomWidget(),
                ),
                Positioned(
                  left: 183.0,
                  top: 369.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 4.0,
                  child: GeneratedLine6Widget(),
                ),
                Positioned(
                  left: 27.0,
                  top: 478.0,
                  right: null,
                  bottom: null,
                  width: 131.0,
                  height: 55.0,
                  child: GeneratedAreaWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
